### ISSUE TITLE
Allow to specify how long nginx logs are stored

### ISSUE THREAD

**Issue by cmeessen** [hifis-net/ansible-role-rsd#83]
If I am correct, the nginx container currently stores the log files for 52 days. This is at least what I assume from looking at `/etc/logrotate.d/nginx`:

```
/var/log/nginx/*.log {
        daily
        missingok
        rotate 52
        compress
        delaycompress
        notifempty
        create 640 nginx adm
        sharedscripts
        postrotate
                if [ -f /var/run/nginx.pid ]; then
                        kill -USR1 `cat /var/run/nginx.pid`
                fi
        endscript
}
```

We need to specify that we can remove logs after X days.

**Comment by tobiashuste** [comment]
@cmeessen If I understand corrrectly something along these lines is what you need.

```yaml
nginx_service:
  logging:
    options:
      max-file: "7"
```

Of course, the value should be configurable.

Probably this is also required for other containers as well.

**Comment by cmeessen** [comment]
@tobiashuste something similar, yes. But using the built-in functionality from docker-compose will not be sufficient. You can only define the maximum file size and the maximum number of files (of the previously defined max file size). This is making it impossible to delete logs after a specified amount of days. I think the best way would be to handle it via `logrotate` inside the container.

**Comment by Normo** [comment]
@cmeessen Then let us move us to https://github.com/research-software-directory/RSD-as-a-service/issues/470 ?

**Comment by cmeessen** [comment]
Yes, I saw your notes in #470 after I commented, and will discuss your suggestions tomorrow morning with the NLeSC team.

**Comment by Normo** [comment]
@cmeessen After some research and tryouts I come to the conclusion to not add more complexity through log rotation to this role. There are already Ansible roles that solve this taks, e.g. https://galaxy.ansible.com/robertdebock/logrotate. I have successfully tested the following example for a default Docker Installation using the `json` logging driver:

```yml
- name: "Apply logrotate config"
  hosts: "all"
  become: true
  roles:
    - role: "robertdebock.logrotate"
      vars:
        # logrotate defaults
        logrotate_frequency: "weekly"
        logrotate_keep: 4
        logrotate_user: "root"
        logrotate_group: "adm"
        logrotate_compress: false

        logrotate_entries:
          - name: "docker-container-logs"
            path: "/var/lib/docker/containers/*/*json.log"
            frequency: "daily"
            keep: 7
            copytruncate: true
            compress: true
            delaycompress: true
            missingok: true
            notifempty: true
```
