### ISSUE TITLE
Support custom themes via mounts

### ISSUE THREAD

**Issue by ruester** [hifis-net/ansible-role-rsd#99]
There is a new change in the RSD coming up: https://github.com/research-software-directory/RSD-as-a-service/pull/506

If this gets merged we will need an option so that some additional docker mounts are made (via `docker-compose.yml`), in case of the HIFIS RSD like so:

```yaml
  frontend:
    ...
    volumes:
      - ./deployment/helmholtz/styles:/app/public/styles
      - ./deployment/helmholtz/data:/app/public/data
      - ./deployment/helmholtz/images:/app/public/images
```

I would think of having some role variable like `rsd_custom_theme` which is unset by default. But if it is set then it is used for additional mounts:

```yaml
  frontend:
    ...
    volumes:
      - ./deployment/{{ rsd_custom_theme }}/styles:/app/public/styles
      - ./deployment/{{ rsd_custom_theme }}/data:/app/public/data
      - ./deployment/{{ rsd_custom_theme }}/images:/app/public/images
```
